#!/bin/sh

ln -f .zshrc       ~/
ln -f .vimrc       ~/
ln -f .gitconfig   ~/
ln -f .Xresources  ~/
xrdb -load ~/.Xresources

ln -f i3/config  ~/.config/i3/
ln -f i3/lock    ~/.config/i3/
ln -f i3/status  ~/.i3status.conf

ln -f update.sh  ~/.update.sh
