#!/bin/sh

ln -f .zshrc       ~/
ln -f .zprofile    ~/
ln -f .tmux.conf   ~/
ln -f .vimrc       ~/
ln -f .gitconfig   ~/
ln -f .Xresources  ~/
ln -f .xinitrc     ~/
xrdb -load ~/.Xresources

ln -f i3/config  ~/.config/i3/
ln -f i3/status  ~/.i3status.conf

if [ "$1" == "--vim" ]; then
	sudo pacman -S $(< vim-plugins)
fi
